### ISSUE TITLE
glycoCT to imagesはどこ？

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/api#1]
api.glytoucan.orgにはないです。

**Comment by yamadaissaku** [comment]
GlycoCT to Image ではないですが、　accessionNumber to image　はこの辺ですね
https://github.com/glytoucan/glyspaceclient/blob/master/src/main/java/org/glyspace/client/GlycanRestClientImpl.java#L181

**Comment by yamadaissaku** [comment]
glyspaceのここでやってますね
https://github.com/glycoinfo/glyspace/blob/master/src/main/java/org/glyspace/registry/utils/ImageGenerator.java#L31

**Comment by yamadaissaku** [comment]
glyspaceのここでやってますね！
https://github.com/glycoinfo/glyspace/blob/master/src/main/java/org/glyspace/registry/utils/ImageGenerator.java#L31

**Comment by aokinobu** [comment]
[この](http://test.api.glytoucan.org/swagger-ui.html#!/glycan-controller/getGlycanImageByStructureUsingPOST)に移動しました。あと、WURCS対応済みです。
